name: Build Executables and Host on GitHub Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pyinstaller --clean -y --onefile main.py

      - name: Archive Binary
        run: mv dist/client ./linux_binary

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: ./linux_binary

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          venv\Scripts\activate
          venv\Scripts\pip install -r requirements.txt
          pyinstaller --clean -y --onefile main.py

      - name: Archive Executable
        run: move dist\client.exe windows_binary.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: ./windows_binary.exe

  build-macos:
    name: Build macOS Binary
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build Binary
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pyinstaller --clean -y --onefile main.py

      - name: Archive Binary
        run: mv dist/client ./macos_binary

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: ./macos_binary